# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
env:
  global:
    - CODECOV_TOKEN='1a2ad6e0-af65-453a-bf74-47ad4c3af843'
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту emelyanoff94@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - emelyanoff94@gmail.com
    on_success: never # default: change
    on_failure: always # default: always